// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRfHwjS-brti38WefCRp9c2ZvqS2494E',
    appId: '1:939360157135:android:334151723099d1c144a6ba',
    messagingSenderId: '939360157135',
    projectId: 'no-fap-fb731',
    storageBucket: 'no-fap-fb731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCd3c6LPlMAZfCS2QHWwDheL9O6nKruwA',
    appId: '1:939360157135:ios:7ca80333cb79fc4644a6ba',
    messagingSenderId: '939360157135',
    projectId: 'no-fap-fb731',
    storageBucket: 'no-fap-fb731.appspot.com',
    iosBundleId: 'com.example.noFap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCd3c6LPlMAZfCS2QHWwDheL9O6nKruwA',
    appId: '1:939360157135:ios:7ca80333cb79fc4644a6ba',
    messagingSenderId: '939360157135',
    projectId: 'no-fap-fb731',
    storageBucket: 'no-fap-fb731.appspot.com',
    iosBundleId: 'com.example.noFap',
  );
}
